---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: agentserver-db-secret
  namespace: agentserver
spec:
  encryptedData:
    database-url: AgB+2P/VTZCV4X4HjHaQ0KMxNiM57bNFKfPyroNGHiN22EJfwD5IfXVS+jQsZmhVyFSCrdPOPGPYNCHewaiwZOdfha12TpfpnivMkt+l4JEZ7MDsNjIiVQUQ47/rueg704czQ1Y+yMfN/v788IWT9t8Ft3QFdfHapB+PagvVVAgVjy7bdTVeDwlWoaoE7d/hS9d2tB1Y/61nk/6Q5+0hwunIAzwQZ3VMaRAtJcmtkvF5cnpwMpI5q1YfTSUd0SnNlCE6ByG4hRVPzX1ZEgH49k2QMNqIPSfoO9hZzf9ThU+gdfCAX2dnSjYePw395TsayV+VBh0w8aFau8xVh51m542viq3zLAqcN3nYXwLD0yqGBTud0XqMsVImQqZq9DAI4Pb//j3H2YH10eR3JGbIyB9B5Hy6A29u18uSq6qtUQGbHGCBUd2eCoL3gryGcLzvLPnO/qLcUeOkocWmTayaJA00AcfkqAPD7ekBZBTNyv0kTS1bBP+TLmfh5HK4FzCHrCkM3H8RTYkXOjbfhYhAJDMT0ovCvxEMfFRdxjJj1cIO6vud567W9adpVjUu3BVyl+y3jCcCl2YM8/HaqN7VfSzk0fReFMBBWfLQMe8w+LZ1D2b/CmnvBdw2cAmvfXldxbD/2RlKGG067kUotHd/+wyGMVtBkqq3LqIP3CEZNYMTdg9sG90kl5U0JnyLp/ZCt06jvPF43zJGcTP0eaFfTYDOIA1QaQATQ93KIRTAxcUkpd2AII761JDwZo+jR6t14YR7XsR/V7WwWzde8dcCxwALXNF1vCDgT7QBveaa0SM9TY2gjv/TkdPrqKB0Fd3pQ/dnMzF7q2o9QX4cOHq9DQnpPBEqSVr3Fr5u9KL1wlCGPKJRVWTimMYPnU0YBJMNl1K4
  template:
    metadata:
      name: agentserver-db-secret
      namespace: agentserver
