---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: agentserver-llmproxy-db-secret
  namespace: agentserver
spec:
  encryptedData:
    database-url: AgBWjiiB6QRYw5fpiKA/ztGG9ZpFqU8IrLse10CxId2FJXmH7A2wUVrWw5hMGNyU1Uu8Y0D+Ysun4HB+ZjlS9TMDVsjo3wLr1rMQ3g+N3Jc3bIeH3NB9tXz163yniChOfHFsxO16YmYz3Us4Oy7uf0+vCbMcGTMGnuCKxn3Trkog66o+AK1UQRI9wlZDwd2JQHHXrjw+mPgk9xNUfXaTi2qc347We7JHZVGEEsLrV5q0xK9Vzqg7chwNOQ2tW3hfcaRGRK5VgeUJGjrQdZ6ORtHWyHk8YLVIQSySnpFwWNy/leX67r+UFu/jxxC5xe1Uh1af5cITKbEpEKNUWHoYkWlFVvWRI5L3kmb5zZWPoqR4yBOXgJARiIJ2Vb6KrLc+URFtOQWzyoDP6aGL+WcAyTnNDHba2ZtFYh+WVjJ/BC40YdcS1bw/+drYdkaLxqqGomk4EnE94XKFxdYKQlRpAN0q0/gm7Y9vzGQ14d2escgOnkWx/VeDf45NicSsJOMP5c35Og512kWkr+PBUPRD7usFGsWFb/2hbbB7aJmaX3URXgFMXzHhCgvRvsAC7yVzKe4PfihCBrjWGnrziUc1mxL3XVgMev7rh0WbT/wgBAprpMydZHWv4UElndyPAl9Wjed37BtOqQnwykampmwp18S4lSFyIF0PXC689PQ/Y/pCSWEzJDm/0k6v8sLmhmcYZILO0OjySTZDRoehig8+zel5VNn7DEBc8DdQlNbKmPdUSDM3BsqajWMPdWTeWzGr6Ew0p4UOoR+QBvK/qy6SdzOefiuhq4wG8G3Ym5k5wb9kxxu0lCY+b3uswBkHFUgv4Gy5aHkmqCYZfnweYAI52RZItIpyqpULvpPyYrlA/6sUaZ1PV5A8X1MDftA=
  template:
    metadata:
      name: agentserver-llmproxy-db-secret
      namespace: agentserver
