---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: agentserver-hydra-db-secret
  namespace: agentserver
spec:
  encryptedData:
    dsn: AgBHieHGX0OwLoRpIsKbzgjh2/1TD2n6rPW6tJrP3+mgAggYDM9R+MnQmjPRkZdP3gdFnTByR9kl5E2t2rQObrUcgag1fgNFmyuLEdhkhyIx66QAQloUzQ6noKXBCUe0e5YnGxPh7oAv73wvNH68xroaSRs8Y4OTeUyCO54GB9M0BjEMNTc6owkZQaCUpTwgTrdGlArbe6ktzYB+k9WEi2SJGqElWEXK+GHr4gjQ6GYTsJ/u6P7nhDcPenLnyH3dPXp+2cJfbsBGAkAVPdKZ2obSHIhQh4JItmlFe65emSYHgKK3S70XYu54E50Rmn3xWzQxUhrEgBbxawZ3gh1bvoGuHJoCVqH+oZ3EZLuCE3iOMJX3snxkg+OZO++n62t43lm3iUHvaU0cGp1Cgu4Sw9/THkPuU/5vN84CiQjaDa5PZV0JRn88XrxnvRNJt2486cWp7yOW3xvnout46JQYsPTQV4Tq7jgPS0Q/3vRYYaahb1uNnXJjvYuGU4nqVQVtxHe8BNu8akwnIDOdnQiotExrTyv9XNeUKFP9bJSJRAVCKSYTcFATtOj69EFdlmMTbrGkp0OdIqM2dE/dEIXqSUZ6JBfjHhAfYHVopGCxpq7Ja3yGeiNVrLL5mdRbm8rJW2aK1WKPfGV9YmD+OOxpR4Z4Y4/+2n5gj28q6uWp0ce6eryO6k/1n0EX3MCAoD1YHdaiuDIAVfoDRKG20thK0+2aNakcIRuHiV5cN++Q2OGFHEmPlJ4nn04xB5oHm77EXE00gctoyRmqPlCkb8O1KIHcchLeiUIwb5FKPJip7lcMBAEc/m691BiqaM2b9rJBzSShVrpopwiEuBHZVgyBQZAEhWAhMt9UnRhy5E8h0Ms40P7prAE9
  template:
    metadata:
      name: agentserver-hydra-db-secret
      namespace: agentserver
