apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    model_list:
    {{- range .Values.models }}
      - model_name: {{ .name }}
        litellm_params:
          model: {{ .model }}
          aws_region_name: {{ $.Values.awsRegion }}
          {{- if .inferenceProfileArn }}
          aws_bedrock_model_id: {{ .inferenceProfileArn }}
          {{- end }}
        model_info:
          mode: chat
    {{- end }}
    litellm_settings:
      drop_params: true
      health_check_interval: 0
