apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    model_list:
    {{- range .Values.models }}
      - model_name: {{ .name }}
        litellm_params:
          model: bedrock/{{ .bedrockModel }}
          aws_region_name: {{ $.Values.awsRegion }}
    {{- end }}
    litellm_settings:
      drop_params: true
