-- Per-workspace WhatsApp webhook verify_token (SaaS isolation).
-- Generated by handleWorkspaceWhatsAppConfigure; used by
-- GET /webhook/whatsapp/{workspace_id} to validate Meta handshake
-- without sharing a single global env-var token across all tenants.
ALTER TABLE workspace_im_channels
  ADD COLUMN IF NOT EXISTS verify_token TEXT;
